config/routes.rb
NewDividendReporter::Application.routes.draw do
  devise_for :admins

  devise_for :users

  root :to => "stocks#index"
  resources :stocks
  resources :users
  get 'stocks/:id/watch' => "stocks#watch", :as => 'stocks_watch'
  get 'pages/help' => "pages#help", :as => 'pages_help'
  get 'users/:id/' => "users#show", :as => 'user_show'
  get 'users/remove_watch/:id' => "users#remove_watch", :as => 'user_remove_watch'
  get 'admin/panel' => "admin#index", :as => 'admin_panel'
  get 'admin/update_quotes' => "admin#update_quotes", :as => 'admin_update_quotes'
  get 'admin/remove_stock/:id' => "admin#remove_stock", :as => 'admin_remove_stock'
  get 'admin/add_stock' => "admin#add_stock", :as => 'admin_add_stock'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :stock, :dependent => :destroy
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates_presence_of :ticker, :company_name
  has_many :quotes
  has_many :user_stock_watches
  has_many :users, :through => :user_stock_watches
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :admin, where(:admin => true)

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :middle_initial, :email, :password, :password_confirmation, :remember_me, :admin
  has_many :stocks, :through => :user_stock_watches
  has_many :user_stock_watches

  def watch stock
    self.user_stock_watches.create(:stock => stock)
  end

  def unwatch stock
    something = self.user_stock_watches.find_by_stock_id stock
    something.destroy
  end
end

app/models/user_stock_watch.rb
class UserStockWatch < ActiveRecord::Base
  #attr_accessible :user_id, :stock_id
  belongs_to :user
  belongs_to :stock
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def update_quotes
    x = YahooIntegrator.new
    ticker_array = []
    stocks = Stock.all
    stocks.each do |stock|
      ticker_array.push(stock.ticker)
    end
    if x.get_quotes(ticker_array)
      flash[:notice] = "All quotes successfully updated"
      redirect_to admin_panel_path
    else
      flash.now[:error] = "Unable to update quotes"
      redirect_to admin_panel_path
    end
  end

  def remove_stock
    if Stock.find(params[:id]).destroy
      flash[:notice] = "Stock successfully removed"
      redirect_to admin_panel_path
    else
      flash.now[:error] = "Unable to remove stock"
      redirect_to admin_panel_path
    end
  end

  def add_stock
    stock = Stock.new
    x = YahooIntegrator.new
    x.get_quotes [params[:ticker]]
    stock.save
    redirect_to admin_panel_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def help
    render :help
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  #before_filter :must_be_logged_in, :only => [:watch]
  def new
  end

  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def watch
    if current_user && stock = Stock.find(params[:id])
      current_user.watch stock
      redirect_to '/'
    elsif !current_user
      render 'pages/must_be_logged_in'
    else
      flash[:error] = "There was a problem adding the stock to your watchlist"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @stocks = current_user.stocks
    else
      redirect_to new_user_session_path
    end
  end

  def remove_watch
    if Stock.find(params[:id])
      @stock = Stock.find(params[:id])
      if current_user
        current_user.unwatch @stock
        flash[:notice] = "Stock successfully removed from watchlist"
        redirect_to user_path(current_user)
      else
        flash.now[:error] = "Stock unsuccessfully removed from watchlist"
        redirect_to user_path(current_user)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.haml
= link_to 'Update all quotes', admin_update_quotes_path
= form_tag(admin_add_stock_path, :method => "get") do
  = label_tag(:ticker, "Add Stock (ticker):")
  = text_field_tag(:ticker)
  = submit_tag("Add Stock")
%table.stocks
  %thead
    %tr
      %th remove
      %th company name
      %th ticker
      %th last price
      %th ex dividend date
      %th dividend pay date
      %th dividend yield
      %th dividend per share
  %tbody
    - @stocks.each do |stock|
      %tr{ :class => cycle("odd", "even") }
        %td= link_to 'remove', admin_remove_stock_path(stock)
        %td= link_to stock.company_name, stock_path(stock)
        %td= stock.ticker
        %td= stock.quotes.last.last_price
        %td= stock.quotes.last.ex_dividend_date
        %td= stock.quotes.last.dividend_pay_date
        %td= stock.quotes.last.dividend_yield
        %td= stock.quotes.last.dividends_per_share

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title NewDividendReporter
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = stylesheet_link_tag 'reset.css'
    = stylesheet_link_tag 'http://yui.yahooapis.com/3.3.0/build/cssgrids/grids-min.css'
    = stylesheet_link_tag 'screen.css'
    = csrf_meta_tag
    #wrapper.yui3-u-1
      #topbar.yui3-u-1
        - if current_user
          = render :partial => "shared/top_bar_logged_in"
        - else
          = render :partial => "shared/top_bar_logged_out"
      #content.yui3-u-1
        = yield
      %body
        .notice 
        = notice
        .alert
        = alert

app/views/pages/help.html.haml
this is the help page

app/views/pages/must_be_logged_in.html.haml
you must be logged in to take advantage of this feature

app/views/shared/_top_bar_logged_in.html.haml
.yui3-u-1
  .yui3-g
    .yui3-u-1-5
      %h1
        = link_to 'Dividend Reporter', root_path
    .yui3-u-4-5
      .top_menu
        = link_to current_user.email, user_path(current_user.id)
          - if current_user && current_user.admin?
          = link_to 'Admin Panel', admin_panel_path
        = link_to 'logout', destroy_user_session_path

app/views/shared/_top_bar_logged_out.html.haml
.yui3-u-1
  .yui3-g
    .yui3-u-1-5
      %h1
        = link_to 'Dividend Reporter', root_path
    .yui3-u-4-5
      .top_menu
        = link_to 'Log in', new_user_session_path
        = link_to 'Help', pages_help_path

app/views/stocks/index.html.haml
%table.stocks
  %thead
    %tr
      %th watch
      %th company name
      %th ticker
      %th last price
      %th ex dividend date
      %th dividend pay date
      %th dividend yield
      %th.last dividend per share
  %tbody
    - @stocks.each do |stock|
      %tr{ :class => cycle("odd", "even") }
        - if current_user && current_user.user_stock_watches.find_by_stock_id(stock.id)
          %td= link_to 'unwatch', user_remove_watch_path(stock)
          %td= link_to stock.company_name, stock_path(stock)
          %td= stock.ticker
          %td= stock.quotes.last.last_price
          %td= stock.quotes.last.ex_dividend_date
          %td= stock.quotes.last.dividend_pay_date
        - else
          %td= link_to 'watch', stocks_watch_path(stock)
          %td= link_to stock.company_name, stock_path(stock)
          %td= stock.ticker
          %td= stock.quotes.last.last_price
          %td= stock.quotes.last.ex_dividend_date
          %td= stock.quotes.last.dividend_pay_date
          %td= stock.quotes.last.dividend_yield
          %td.last= stock.quotes.last.dividends_per_share

app/views/stocks/show.html.haml
="Stock Information : " +  @stock.company_name + " (" + @stock.ticker + ")"
%table
  %thead
    %tr
      %th some sort of company info

app/views/users/show.html.haml
- if UserStockWatch.find_by_user_id(current_user.id) != nil
  %table.userstockwatches
    %thead
      %tr
        %th remove
        %th company name
        %th ticker
        %th last price
        %th ex dividend date
        %th dividend pay date
        %th dividend yield
        %th dividend per share
    %tbody
      - @stocks.each do |stock|
        %tr{ :class => cycle("odd", "even") }
          %td= link_to 'remove', user_remove_watch_path(stock)
          %td= link_to stock.company_name, stock_path(stock)
          %td= stock.ticker
          %td= stock.quotes.last.last_price
          %td= stock.quotes.last.ex_dividend_date
          %td= stock.quotes.last.dividend_pay_date
          %td= stock.quotes.last.dividend_yield
          %td= stock.quotes.last.dividends_per_share

- else